name: Playwright Tests

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checks the code out from the repo so the following steps have access
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Installs .NET SDK on vm where tests are ran
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'
        
    - name: Install dependencies
      run: dotnet restore

    - name: Install Playwright Browsers
      run: npx playwright install
    
    # Building to catch any build errors before running
    - name: Build
      run: dotnet build --configuration Release

    - name: Run Application
      run: dotnet run --no-build --configuration Release &

    # Waiting a few seconds to ensure app is running
    - name: Wait for application to start
      run: sleep 5
    
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
