name: Playwright Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checks the code out from the repo so the following steps have access
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Installs .NET SDK on vm where tests are ran
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'
        
    - name: Install dependencies
      run: dotnet restore

    # Building to catch any build errors before running and create script for playwright broswer installation
    - name: Build
      run: dotnet build

    - name: Install Playwright Browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Application
      run: dotnet run --no-build &

    # Waiting a few seconds to ensure app is running
    - name: Wait for application to start
      run: sleep 5
    
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
